### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ST-DDT**
[Forum](https://forums.factorio.com/viewtopic.php?f=93&t=6847&p=151908#p151908)

This is the German translation for this mod.

If I have missed a file that needs translation or you need a translation for a future update please ping me.

PS: Thanks for this awesome mod.

### CODE REVIEW

**Comment by Choumiko** [comment]
Wow it really is Waggon.. i would have gone with Wagon (german myself xD)
Thanks

**Comment by ST-DDT** [comment]
I thought so myself, but then i glanced at Factorio's "Güterwaggon" couldn't believe it and then glanced at Duden just to be sure.

**Comment by yoshuamongrain** [comment]
apparently the propper German word is 'Kesselwagen', not 'Tankwaggon'

https://de.wikipedia.org/wiki/Kesselwagen

**Comment by ST-DDT** [comment]
The issue with that word is that you cannot image clearly what this is if you don't know what it is (IMO).
I used google images search results to check whether other people declared their rail tanker like any of these

| Term | Results |
| --- | --- |
| Tankwaggon | 14.5k |
| Kesselwaggon | 12k |
| Kesselwagen | 402k |

My main concern is the "Wagen" (any vehicle/too generic) part vs. the "Waggon" (train) part. 
(Especially since "Tankwagen" is a street bound vehicle)
Although "Kesselwagen" might be the proper term for it.

**Pull request merged**
